---
output:
  pdf_document: default
  html_document: default
---

---
title: \textbf{Project 6}
author: "Juwon Lee, Economics and Statistics, UCLA"
date: "2023-05-02"
output: 
  pdf_document:
    latex_engine: xelatex
---

tinytex::install_tinytex()

### a.

```{r}

hw <- read.csv("/Users/user/Desktop/Yonsei/Junior/3-2/Statistical Models in Finance/stockData.csv",sep=',', header=T)

r_hw6 <- (hw[-1, 3:ncol(hw)]-hw[-nrow(hw),3:ncol(hw)])/hw[-nrow(hw),3:ncol(hw)]

covmat_hw6 <- cov(r_hw6)
beta_hw6 <- covmat_hw6[1,-1] / covmat_hw6[1,1]

rrr_hw6 <- r_hw6[,-c(1,which(beta_hw6<0)+1)]

beta_new_hw6 <- rep(0,ncol(rrr_hw6))
alpha_hw6 <- rep(0,ncol(rrr_hw6))
mse_hw6 <- rep(0,ncol(rrr_hw6))
Ribar_hw6 <- rep(0,ncol(rrr_hw6))
Ratio_hw6 <- rep(0,ncol(rrr_hw6))
stock_hw6 <- rep(0,ncol(rrr_hw6))

rf_hw6 <- 0.001

for(i in 1:ncol(rrr_hw6)) {
  q_hw6 <- lm(data=rrr_hw6, formula=rrr_hw6[,i]~r_hw6[,1])
  beta_new_hw6[i] <- q_hw6$coefficients[2]
  alpha_hw6[i] <- q_hw6$coefficients[1]
  mse_hw6[i] <- summary(q_hw6)$sigma^2
  Ribar_hw6[i] <- q_hw6$coefficients[1] + q_hw6$coefficients[2] * mean(r_hw6[,1])
  Ratio_hw6[i] <- (Ribar_hw6[i] - rf_hw6) / beta_new_hw6[i]
  stock_hw6[i] <- i
}

xx_hw6 <- (cbind(stock_hw6, alpha_hw6, beta_new_hw6, Ribar_hw6, mse_hw6, Ratio_hw6))

A_hw6 <- xx_hw6[order(-xx_hw6[,6]),]

```

### b.

\noindent 1. If short sales are allowed:

```{r}

col1_hw6 <- rep(0,nrow(A_hw6))
col2_hw6 <- rep(0,nrow(A_hw6))
col3_hw6 <- rep(0,nrow(A_hw6))
col4_hw6 <- rep(0,nrow(A_hw6))
col5_hw6 <- rep(0,nrow(A_hw6)) 

col1_hw6 <- (A_hw6[,4]-rf_hw6)*A_hw6[,3]/A_hw6[,5]
col3_hw6 <- A_hw6[,3]^2 / A_hw6[,5]
for(i in 1:nrow(A_hw6)) {
  col2_hw6[i] <- sum(col1_hw6[1:i])
  col4_hw6[i] <- sum(col3_hw6[1:i])
}

head(cbind(A_hw6, col1_hw6, col2_hw6, col3_hw6, col4_hw6))

for(i in 1:nrow(A_hw6)) {
  col5_hw6[i] <- var(r_hw6[,1])*col2_hw6[i]/(1+var(r_hw6[,1])*col4_hw6[i])
}

z_short_hw6 <- (A_hw6[,3]/A_hw6[,5])*(A_hw6[,6]-col5_hw6[nrow(A_hw6)])
x_short_hw6 <- z_short_hw6/sum(z_short_hw6)

Weights_with_short_hw6 <- cbind(A_hw6, col1_hw6, col2_hw6, col3_hw6, col4_hw6, col5_hw6, z_short_hw6, x_short_hw6)

Weights_with_short_hw6[,13]

```

\noindent 2. If short sales are NOT allowed:

```{r}

table1_hw6 <- cbind(A_hw6, col1_hw6, col2_hw6, col3_hw6, col4_hw6, col5_hw6)
table2_hw6 <- table1_hw6[1:which(col5_hw6==max(col5_hw6)),]

z_no_short_hw6 <- (table2_hw6[,3]/table2_hw6[,5]) * (table2_hw6[,6] - max(col5_hw6))
  
x_no_short_hw6 <- z_no_short_hw6 / sum(z_no_short_hw6)
  
Weights_no_short_hw6 <- cbind(table2_hw6, z_no_short_hw6, x_no_short_hw6)

Weights_no_short_hw6[,13]

```

```{r}

r_2_hw6 <- r_hw6[,A_hw6[,1]]

means_hw6 <- colMeans(r_2_hw6)
covmat_hw6 <- cov(r_2_hw6)
corrmat_hw6 <- cor(r_2_hw6)
variances_hw6 <- diag(covmat_hw6)
stdev_hw6 <- diag(covmat_hw6)^.5

ones_hw6 <- rep(1,30)

A_plot_hw6 <- sum(covmat_hw6^(-1) * means_hw6)
A2_plot_hw6 <- t(ones_hw6) %*% solve(covmat_hw6) %*% means_hw6
B_plot_hw6 <- sum(covmat_hw6^(-1) * means_hw6 * means_hw6)
B2_plot_hw6 <- t(means_hw6) %*% solve(covmat_hw6) %*% means_hw6
C_plot_hw6 <- sum(covmat_hw6^(-1))
C2_plot_hw6 <- t(ones_hw6) %*% solve(covmat_hw6) %*% ones_hw6
D_plot_hw6 <- B_plot_hw6 * C_plot_hw6 - A_plot_hw6 * A_plot_hw6
D2_plot_hw6 <- B2_plot_hw6 * C2_plot_hw6 - A2_plot_hw6 * A2_plot_hw6

x_plot_hw6 <- seq(-0.1,0.1, 0.001)
sigma_squared_hw6 <- (C2_plot_hw6 * x_plot_hw6 * x_plot_hw6 - 2 * A2_plot_hw6 * x_plot_hw6 + B2_plot_hw6) / D2_plot_hw6

#minvar_hw6 <- 1/C2_plot_hw6
#minE_hw6 <- A2_plot_hw6 / C2_plot_hw6
#sdeff_hw6 <- seq((minvar_hw6)^.5,1, by=0.0001)
#plot(sdeff_hw6, x_plot_hw6)

### 1. Short sales are allowed
mean_with_short_hw6 <- t(as.matrix(A_hw6[,4])) %*% as.matrix(Weights_with_short_hw6[,13])
var_with_short_hw6 <- t(as.matrix(Weights_with_short_hw6[,13])) %*% covmat_hw6 %*% as.matrix(Weights_with_short_hw6[,13])

### 2. Short sales are NOT allowed
covmat_no_short_hw6 <- cov(r_2_hw6[,1:11])

mean_no_short_hw6 <- t(as.matrix(A_hw6[1:11,4])) %*% as.matrix(Weights_no_short_hw6[,13])
var_no_short_hw6 <- t(as.matrix(Weights_no_short_hw6[,13])) %*% covmat_no_short_hw6 %*% as.matrix(Weights_no_short_hw6[,13])

plot(sigma_squared_hw6, x_plot_hw6, type='l')
points(variances_hw6, means_hw6)
points(var(r_hw6$X.GSPC), mean(r_hw6$X.GSPC), col='blue')
points(var_with_short_hw6, mean_with_short_hw6, col='red')
points(var_no_short_hw6, mean_no_short_hw6, col='red')
text(0.002, -0.015, "S&P 500", col='blue')
text(0.004, 0.06, "Allowed", col='red')
text(0.0022, 0.045, "NOT \n Allowed", col='red')

```

### c.

```{r}

a <- read.csv("/Users/user/Desktop/Yonsei/Junior/3-2/Statistical Models in Finance/stockData.csv", sep=",", header=TRUE)

r <- (a[-1,3:ncol(a)]-a[-nrow(a),3:ncol(a)])/a[-nrow(a),3:ncol(a)]

covmat <- var(r)
beta <- covmat[1,-1] / covmat[1,1]

rrr <- r[,-c(1,which(beta<0)+1)]  

Rfr <- seq(-0.05,.01,0.0005)

rbar_opt <- rep(0,length(Rfr))
risk_opt <- rep(0,length(Rfr))

length(Rfr)

for(l in 1:length(Rfr)){
rf <- Rfr[l]

beta <- rep(0,ncol(rrr))
alpha <- rep(0,ncol(rrr))
mse <- rep(0,ncol(rrr))
Ribar <- rep(0,ncol(rrr))
Ratio <- rep(0,ncol(rrr))
stocknum <- rep(0,ncol(rrr))

for(i in 1:ncol(rrr)){
	q <- lm(data=rrr, formula=rrr[,i] ~ r[,1])
	beta[i] <- q$coefficients[2] 
	alpha[i] <- q$coefficients[1] 
     mse[i] <- summary(q)$sigma^2
	Ribar[i] <- q$coefficients[1]+q$coefficients[2]*mean(r[,1])
	Ratio[i] <- (Ribar[i]-rf)/beta[i]
    stocknum[i] <- i
}

xx <- (data.frame(stocknum,alpha, beta, Ribar, mse, Ratio))

A <- xx[order(-xx[,6]),]

col1 <- rep(0,nrow(A))
col2 <- rep(0,nrow(A))
col3 <- rep(0,nrow(A))
col4 <- rep(0,nrow(A))
col5 <- rep(0,nrow(A))

col1 <- (A[,4]-rf)*A[,3]/A[,5]
col3 <- A[,3]^2/A[,5]
for(i in(1:nrow(A))) {
col2[i] <- sum(col1[1:i])
col4[i] <- sum(col3[1:i])
}

cbind(A, col1, col2, col3, col4)

for(i in (1:nrow(A))) {
col5[i] <- var(r[,1])*col2[i]/(1+var(r[,1])*col4[i])
}


#The final table when short sales allowed:
B <- cbind(A, col1, col2, col3, col4, col5)
rownames(B) <- NULL

#SHORT SALES NOT ALLOWED:
table2 <- B[1:which(col5==max(col5)), ]

z_no_short <- (table2[,3]/table2[,5])*(table2[,6]-max(col5))
x_no_short <- z_no_short/sum(z_no_short)

r1 <- data.frame(rrr[,table2[,1]])

beta1 <- rep(0,ncol(r1))
sigma_e1 <- rep(0,ncol(r1))
alpha1 <- rep(0,ncol(r1))

for(i in 1:ncol(r1)){
	q1<- lm(r1[,i] ~ r[,1])
beta1[i] <- q1$coefficients[2] 
sigma_e1[i] <- summary(q1)$sigma^2
alpha1[i] <- q1$coefficients[1] 
} 

means1 <- colMeans(r1)

xx <- rep(0,ncol(r1)*(ncol(r1)))          
varcovar <- matrix(xx,nrow=ncol(r1),ncol=ncol(r1)) 


for (i in 1:ncol(r1)){
	for (j in 1:ncol(r1)){
		varcovar[i,j]=beta1[i]*beta1[j]*var(r[,1])
		if(i==j){varcovar[i,j]=beta1[i]^2*var(r[,1])+ sigma_e1[i]}
		}
		}
		

rbar_opt[l] <- t(x_no_short) %*% means1
risk_opt[l] <- ( t(x_no_short) %*% varcovar %*% x_no_short )^.5

}

plot(risk_opt, rbar_opt, type="l", main="Efficient frontier when short sales not allowed", ylab="Portfolio expected return", xlab="Portfolio standard deviation")

```

### d.

```{r}

average_corr_hw6 <- (sum(cor(r_hw6[-1])) - 30) / (length(r_hw6[-1]) * (length(r_hw6[-1]) - 1))

Ribar_Rf <- Ribar_hw6 - rf_hw6

sigma_i_hw6 <- rep(0, ncol(rrr_hw6))
corr_rate_hw6 <- rep(0, ncol(rrr_hw6))
stacked_i_hw6 <- rep(0, ncol(rrr_hw6))
c_i_hw6 <- rep(0, ncol(rrr_hw6))
ratio_sigma <- rep(0, ncol(rrr_hw6))

for(i in 1:ncol(rrr_hw6)) {
  sigma_i_hw6[i] <- sd(rrr_hw6[,i])
  corr_rate_hw6[i] <- average_corr_hw6 / (1 - average_corr_hw6 + i * average_corr_hw6)
  ratio_sigma[i] <- Ribar_Rf[i] / sigma_i_hw6[i]
  stacked_i_hw6[i] <- sum(ratio_sigma[1:i])
  c_i_hw6[i] <- (1 / (1 - average_corr_hw6) * sigma_i_hw6[i]) * stacked_i_hw6[i]
}

table_ccm_hw6 <- cbind(stock_hw6, Ribar_hw6, Ribar_Rf, sigma_i_hw6, ratio_sigma, corr_rate_hw6, stacked_i_hw6, c_i_hw6) 
table_ccm_hw6

```

### e.

```{r}

### 1. Short sales are allowed

z_with_short_ccm_hw6 <- rep(0, ncol(rrr_hw6))

for (i in 1:ncol(rrr_hw6)) {
  z_with_short_ccm_hw6[i] <- 1 / ((1 - average_corr_hw6) * sigma_i_hw6[i]) * (ratio_sigma[i] - c_i_hw6[i])
}

x_with_short_ccm_hw6 <- z_with_short_ccm_hw6 / sum(z_with_short_ccm_hw6)

mean_with_short_ccm_hw6 <- t(as.matrix(Ribar_hw6)) %*% as.matrix(x_with_short_ccm_hw6)
var_with_short_ccm_hw6 <- t(as.matrix(x_with_short_ccm_hw6)) %*% covmat_hw6 %*% as.matrix(x_with_short_ccm_hw6)

### 2. Short sales are NOT allowed

table_ccm_2_hw6 <- table_ccm_hw6[order(-table_ccm_hw6[,5]),]

table_ccm_3_hw6 <- cbind(table_ccm_2_hw6, table_ccm_2_hw6[,5] - table_ccm_2_hw6[,8])

table_ccm_4_hw6 <- table_ccm_3_hw6[order(-table_ccm_3_hw6[,9]),]
table_ccm_4_hw6

table_ccm_4_hw6[,1][14:30]

z_no_short_ccm_hw6 <- rep(0, 13)

for (i in 1:13) {
  z_no_short_ccm_hw6[i] <- (1 / (1-average_corr_hw6) * table_ccm_4_hw6[,4][i]) * (table_ccm_4_hw6[,7][i] - table_ccm_4_hw6[,8][i])
}

z_no_short_ccm_hw6

x_no_short_ccm_hw6 <- z_no_short_ccm_hw6 / sum(z_no_short_ccm_hw6)

covmat_no_short_hw6 <- cov(r_2_hw6[,-table_ccm_4_hw6[,1][14:30]])

mean_no_short_ccm_hw6 <- t(as.matrix(table_ccm_2_hw6[1:13,2])) %*% as.matrix(x_no_short_ccm_hw6)
var_no_short_ccm_hw6 <- t(as.matrix(x_no_short_ccm_hw6)) %*% covmat_no_short_hw6 %*% as.matrix(x_no_short_ccm_hw6)

plot(sigma_squared_hw6, x_plot_hw6, type='l',  ylab="Portfolio expected return", xlab="Portfolio standard deviation")
points(variances_hw6, means_hw6)
points(var(r_hw6$X.GSPC), mean(r_hw6$X.GSPC), col='blue')
points(var_with_short_hw6, mean_with_short_hw6, col='red')
points(var_no_short_hw6, mean_no_short_hw6, col='red')
points(var_no_short_ccm_hw6, mean_no_short_ccm_hw6, col='orange')
points(var_with_short_ccm_hw6, mean_with_short_ccm_hw6, col='orange')
text(0.001, 0.045, "(CCM) NOT \n Allowed", col='orange')
text(0.004, -0.03, "(CCM) Allowed", col='orange')
text(0.0014, -0.012, "S&P 500", col='blue')
text(0.004, 0.06, "Allowed", col='red')
text(0.0022, 0.045, "NOT \n Allowed", col='red')

```
