---
title: "HW2"
author: "Juwon Lee"
date: "2023-04-09"
output:
  pdf_document: default
  html_document: default
---

---
title: \textbf{Homework 2}
author: "Juwon Lee, Economics and Statistics, Yonsei University"
date: "2023-04-17"
output: 
  pdf_document:
    latex_engine: xelatex
---

tinytex::install_tinytex()

### Project 1.

#### a.

```{r}

hw2 <- read.csv("/Users/user/Desktop/Yonsei/Junior/3-2/Statistical Models in Finance/stockData.csv",
                sep=',', header=T)

r_hw2 <- (hw2[-1, 3:ncol(hw2)]-hw2[-nrow(hw2),3:ncol(hw2)])/hw2[-nrow(hw2),3:ncol(hw2)]

means_hw2 <- colMeans(r_hw2[-1])

covmat_hw2 <- cov(r_hw2[-1])

corrmat_hw2 <- cor(r_hw2[-1])

variances_hw2 <- diag(covmat_hw2)

stdev_hw2 <- diag(covmat_hw2)^(0.5)

plot(stdev_hw2, means_hw2)

equal_means <- mean(means_hw2)

equal_stdev <- (1/(length(r_hw2[-1])-1)*mean(stdev_hw2)^2 + (length(r_hw2[-1])-1)/length(r_hw2[-1])*mean(covmat_hw2))^(1/2)

plot(stdev_hw2, means_hw2)
points(equal_stdev, equal_means, col='red')

A_hw2 <- sum(covmat_hw2^(-1) * means_hw2)

B_hw2 <- sum(covmat_hw2^(-1) * means_hw2 * means_hw2)

C_hw2 <- sum(covmat_hw2^(-1))

D_hw2 <- B_hw2 * C_hw2 - A_hw2 * A_hw2

y1_hw2 <- seq(-1, 1, 0.001)

x1_hw2 <- ((C_hw2 * y1_hw2^2 - 2 * A_hw2 * y1_hw2 + B_hw2) / D_hw2)^(1/2)

plot(stdev_hw2, means_hw2)
points(equal_stdev, equal_means, col='red')
lines(x1_hw2, y1_hw2, col='red')

```

\noindent Thus, we can compute it.

```{r}

A_hw2 ; B_hw2 ; C_hw2 ; D_hw2

```

\noindent $A = 17610.72, B = 278.0063, C = 1116755, D = 327510.6$.

#### b.

```{r}

E_hw2 <- equal_means
E_hw2

lambda1_hw2 <- (C_hw2 * E_hw2 - A_hw2) / D_hw2
lambda2_hw2 <- (B_hw2 - A_hw2 * E_hw2) / D_hw2

lambda1_hw2 ; lambda2_hw2

```

\noindent Thus, $\lambda_1 = -0.01160415, \lambda_2 = 0.0001838876$.

#### c, d.

```{r}

x_hw2 <- seq(-0.2, 0.2, 0.001)

sigma_squared_hw2 <- (C_hw2 * x_hw2 * x_hw2 - 2 * A_hw2 * x_hw2 + B_hw2) / D_hw2

plot(x_hw2, sigma_squared_hw2, type='l')
points(E_hw2, lambda1_hw2 * E_hw2 + lambda2_hw2, col='red')

```

#### e.

```{r}

plot(sigma_squared_hw2, x_hw2, type='l')
points(stdev_hw2, means_hw2)
points(equal_stdev, equal_means, col='red')
points(var(r_hw2$X.GSPC), mean(r_hw2$X.GSPC), col='blue')
points(lambda1_hw2 * E_hw2 + lambda2_hw2, E_hw2, col='darkgreen')
text(0.005, -0.03, "S&P500", col='blue')
text(0.01, 0.05, "Minimum Risk", col='darkgreen')
text(0.05, 0.05, "Equal Allocation", col='red')
text(0.12, 0.16, "(c)")

```

```{r}

seq_hw2 <- seq(-30, -2, 2)

odd_means_hw2 <- colMeans(r_hw2[-1,seq_hw2])

odd_covmat_hw2 <- cov(r_hw2[-1,seq_hw2])

odd_corrmat_hw2 <- cor(r_hw2[-1,seq_hw2])

odd_variances_hw2 <- diag(odd_covmat_hw2)

odd_stdev_hw2 <- diag(odd_covmat_hw2)^(0.5)

odd_means <- mean(odd_means_hw2)

odd_stdev <- (1/(length(r_hw2[-1])/2-1)*mean(odd_stdev_hw2)^2 + (length(r_hw2[-1])/2-1)/length(r_hw2[-1])/2*mean(odd_covmat_hw2))^(1/2)

seq2_hw2 <- seq(-29, -1, 2)

even_means_hw2 <- colMeans(r_hw2[-1,seq2_hw2])

even_covmat_hw2 <- cov(r_hw2[-1,seq2_hw2])

even_corrmat_hw2 <- cor(r_hw2[-1,seq2_hw2])

even_variances_hw2 <- diag(even_covmat_hw2)

even_stdev_hw2 <- diag(even_covmat_hw2)^(0.5)

even_means <- mean(even_means_hw2)

even_stdev <- (1/(length(r_hw2[-1])/2-1)*mean(even_stdev_hw2)^2 + (length(r_hw2[-1])/2-1)/length(r_hw2[-1])/2*mean(even_covmat_hw2))^(1/2)

seq3_hw2 <- c(20:27)  
  
finance_means_hw2 <- colMeans(r_hw2[-1,seq3_hw2])

finance_covmat_hw2 <- cov(r_hw2[-1,seq3_hw2])

finance_corrmat_hw2 <- cor(r_hw2[-1,seq3_hw2])

finance_variances_hw2 <- diag(finance_covmat_hw2)

finance_stdev_hw2 <- diag(finance_covmat_hw2)^(0.5)

finance_means <- mean(finance_means_hw2)

finance_stdev <- (1/(length(seq3_hw2)-1)*mean(finance_stdev_hw2)^2 + (length(seq3_hw2)-1)/length(seq3_hw2)*mean(finance_covmat_hw2))^(1/2)


plot(sigma_squared_hw2, x_hw2, type='l')
points(stdev_hw2, means_hw2)
points(equal_stdev, equal_means, col='red')
points(var(r_hw2$X.GSPC), mean(r_hw2$X.GSPC), col='blue')
points(lambda1_hw2 * E_hw2 + lambda2_hw2, E_hw2, col='darkgreen')
points(odd_stdev, odd_means, col='orange')
points(even_stdev, even_means, col='hotpink')
points(finance_stdev, finance_means, col='purple')
text(0.005, -0.03, "S&P500", col='blue')
text(0.008, 0.05, "Minimum \n Risk", col='darkgreen')
text(0.053, 0.053, "Equal \n Allocation", col='red')
text(0.033, 0.052, "Even \n Index", col='hotpink')
text(0.029, -0.034, "Odd \n Index", col='orange')
text(0.051, -0.031, "Finance \n Firms", col='purple')
text(0.12, 0.16, "(c)")

```
